name: Trigger Algolia Crawler (PR)
on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  algolia_recrawl:
    name: Algolia Recrawl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Get deployment URL
        id: deployment
        uses: dorshinar/get-deployment-url@master
        timeout-minutes: 1
        with:
          token: ${{ github.token }}

      - name: Vercel-PR => Algolia crawler creation and recrawl on preview (Pull Request)
        uses: algolia/algoliasearch-crawler-github-actions@latest
        id: crawler_pr
        with:
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: ${{ steps.deployment.outputs.deployment }}
          override-config: true
